[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['rm -rf node_modules', 'npm install --legacy-peer-deps']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npx vite preview --host 0.0.0.0 --port $PORT'
